common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="common/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from twitter import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('twitter/', include('twitter.urls')),
    path('common/', include('common.urls')), 
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/urls.py
from django.urls import path
from . import views

app_name = 'twitter'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.twit_create, name='twit_create'),
    path('delete/<int:twit_id>', views.twit_delete, name='twit_delete'),
    path('<int:twit_id>/', views.detail, name='detail'),
    path('user/<int:user_id>/', views.mypage, name='mypage'),
]

common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    phone = models.CharField('phone', blank=True, max_length=20)
    pp = models.ImageField(upload_to='', null=True, blank=True)
    title = models.CharField('title', max_length=64, blank=True)
    class Meta:
        db_table = 'user'

twitter/models.py
from django.db import models
from django.contrib.auth import get_user_model # User 모델 (settings => AUTH_USER_MODEL)
# from django.conf import settings

class Twit(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.content
    
    def get_all_children(self):
        twit_list = list(self.children.all())
        # if twit_list:
        #     twit_list.extend(list(twit_list)) # extend : 리스트 끝에 항목 추가 (extend와 append의 차이?)
        return twit_list
    
    def get_my_children(self):
        count = self.children.all().count()
        return count


# child -> parent
# parent -> children

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from common.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email", "pp")

class UserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User
        fields = ("username", "email", "pp")

twitter/forms.py
from django import forms
from twitter.models import Twit

class TwitForm(forms.ModelForm):
    class Meta:
        model = Twit
        fields = ['content', 'parent']

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.contrib.auth.decorators import login_required

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username = username, password = raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

twitter/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Twit
from django.contrib.auth import get_user_model # User 모델 (settings => AUTH_USER_MODEL)
from django.utils import timezone
from .forms import TwitForm
from django.views.decorators.http import require_POST
from common.forms import UserForm, UserChangeForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404

def index(request):
    page_query = 1
    twits = Twit.objects.order_by('-create_date')
    paginator = Paginator(twits, page_query * 10) # 트위터 10개씩
    page = request.GET.get('page', page_query) # 현재페이지 쿼리 파라미터

    try:
        page_obj = paginator.page(page)
    except (EmptyPage, PageNotAnInteger): # 초과된 페이지일 경우 데이터x
        print("트윗이 없습니다.")
        raise Http404("페이지가 존재하지 않습니다.")

    context = {'twits': page_obj}
    return render(request, 'twitter/main.html', context)

def detail(request, twit_id):
    thread = []
    thistwit = get_object_or_404(Twit, pk=twit_id)

    children = thistwit.get_all_children()
    for child in children:
        thread.append({'id': child.id, 'parent_id': child.parent_id, 'content': child.content, 'author': child.author.username, 'create_date': child.create_date, "pp": child.author.pp})

    context = {'thread': thread, 'thistwit': thistwit}
    return render(request, 'twitter/twit_detail.html', context)


@login_required(login_url='common:login')
@require_POST
def twit_create(request):
    form = TwitForm(request.POST)
    if form.is_valid():
        twit = form.save(commit=False)
        twit.author = request.user
        twit.create_date = timezone.now()
        twit.save()
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found')) # post 후 현재 페이지에서 리다이렉트
    else:
        messages.error(request, form.errors)
        return redirect('twitter:index')

@login_required(login_url='common:login')
def twit_delete(request, twit_id):
    twit = get_object_or_404(Twit, pk=twit_id)
    if request.user != twit.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('twit:detail', twit_id=twit.id)
    twit.delete()
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found')) # post 후 현재 페이지에서 리다이렉트


@login_required(login_url='common:login')
def mypage(request, user_id):    
    if request.method =="POST" and request.user.id == user_id :
        form = UserChangeForm(request.POST, request.FILES, instance=request.user, )
        if form.is_valid():
            form.save()
            return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
    else:
        form = UserChangeForm(instance=request.user)
    
    page_query = 1
    twits = Twit.objects.filter(author_id=user_id).order_by('-create_date')
    my_twit = get_user_model().objects.get(pk=user_id)
    paginator = Paginator(twits, page_query * 10) # 트위터 10개씩
    page = request.GET.get('page', page_query) # 현재페이지 쿼리 파라미터

    try:
        page_obj = paginator.page(page)
    except (EmptyPage, PageNotAnInteger): # 초과된 페이지일 경우 데이터x
        print("트윗이 없습니다.")
        raise Http404("페이지가 존재하지 않습니다.")

    context = {'form': form, 'twits': page_obj, "my_twit": my_twit }
    return render(request, 'twitter/my_twits.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- Our project just needs Font Awesome Free's Solid and Brand files -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"/>
    <title>Twitter</title>
</head>
<body>
    {% include "nav.html" %}
    <div class="infinite">
    {% block content %}
    {% endblock %}
    </div>  
    <div class="top">TOP</div>
    <div class="pagination"></div>
    {% block script %}
    <script>
        const topBtn = document.querySelector('.top')
        topBtn.addEventListener("click", () => {
            window.scrollTo({
                top:0,
                behavior:'smooth'
            })
        })

        // 답글 form 노출
        const replyEvent = (e) => {
            const replyForm = e.currentTarget.parentNode.nextElementSibling
            
            if(replyForm.style.display === "none"){
                replyForm.style.display = "flex"
            }
            else replyForm.style.display = "none"
        }

        // 트윗 삭제 경고
        const deleteEvent = (e) => {
            if(confirm("정말로 삭제하시겠습니까?")){
                location.href = e.currentTarget.dataset.uri
            }
        }

        // 답글, 삭제 클릭이벤트
        function btnFunction() {
            const replyBtns = document.getElementsByClassName("reply-btn")
            Array.from(replyBtns).forEach((e) => {
                e.addEventListener('click', replyEvent)
            })
        
            const delete_btns = document.getElementsByClassName("delete-btn")
            Array.from(delete_btns).forEach(function(e){
                e.addEventListener('click', deleteEvent)
            })

            // 프로필 수정모드 toggle
            let settingMode = false
            const settingBtns = document.getElementsByClassName("setting-btn")
            const profile = document.getElementsByClassName("profile")[0]
            const profileText = document.getElementsByClassName("profile-text-wrap")[0]
            const profileForm = document.getElementsByClassName("profile-form-wrap")[0]

            Array.from(settingBtns).forEach(function(e) {
                e.addEventListener('click', function(){
                    if(settingMode === false){
                        profile.classList.add("setting-mode")
                        settingMode = true
                        profileText.style.display = "none"
                        profileForm.style.display = "flex"
                    }
                    else {
                        profile.classList.remove("setting-mode")
                        settingMode = false
                        profileText.style.display = "flex"
                        profileForm.style.display = "none"
                    }
                })
            })
        }
        btnFunction()

        // 이미지 썸네일 미리보기
        function setThumbnail(event) {
            for (var image of event.target.files) {
              var reader = new FileReader();
    
              reader.onload = function(event) {
                const imgContainer = document.querySelector("div#image_container")
                var img = document.createElement("img");
                img.classList.add('new-pp')
                const newPP = document.querySelector(".new-pp")

                // 미리보기 이미지 무한 추가 방지
                if (imgContainer.children.length <= 0) {
                    img.setAttribute("src", event.target.result);
                    imgContainer.appendChild(img);
                }
                else {
                    newPP.remove()
                    img.setAttribute("src", event.target.result);
                    imgContainer.appendChild(img);
                }
                // 미리보기 이미지 추가시 기존 프로필 이미지 숨김처리
                document.querySelector(".now-pp").style.opacity = "0"
                console.log(imgContainer.children.length)
              };
    
              console.log(image);
              reader.readAsDataURL(image);
            }
        }
        
        // 무한스크롤 구현
        const url = window.location.href
        const currentUrl = url.split('?page=')[0] // 현재페이지 주소
        const urlParam = window.location.search
        const searchParams = new URLSearchParams(urlParam)
        const param = !searchParams.get('page') ? '1' : searchParams.get('page') // page param이 없는 경우 ?page=1
        let page = Number(param)

        function loadMoreData() {
            fetch(`${currentUrl}?page=${page + 1}`)
            .then(res => res.text())
            .then(data => {
                const stringToHTML = (str) => {
                    var dom = document.createElement('div');
                    dom.innerHTML = str;
                    return dom;
                };
                const twitBoxes = stringToHTML(data).querySelectorAll('.twit-box')
                const nextTwits = stringToHTML(data).querySelector('.twit-list')

                if(twitBoxes.length > 0) {
                    const twitList = document.querySelector('.twit-area')
                    twitList.appendChild(nextTwits)
                    page++
                }
                else {
                    console.log('No more data')
                }
                btnFunction()
            })
          }

          window.addEventListener('scroll', () => {
            let scrollLocation = document.documentElement.scrollTop; // 현재 스크롤바 위치
            let windowHeight = window.innerHeight; // 스크린 창 height
            let fullHeight = document.body.scrollHeight ; 
        
            if(scrollLocation + windowHeight >= fullHeight){
                loadMoreData()
                console.log(page + 1)
            }
        })

        

    </script>
    {% endblock %}
</body>
</html>

templates/common/login.html
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="contiainer">
    <form action="{% url 'common:signup' %}" method="post" class="signup-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="signup-form-wrap">
            <div>
                <label for="username">사용자 이름</label>
                <input type="text" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div>
                <label for="password1">비밀번호</label>
                <input type="password" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
            </div>
            <div>
                <label for="password2">비밀번호 확인</label>
                <input type="password" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
            </div>
            <div>
                <label for="email">이메일</label>
                <input type="text" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/nav.html
{% block script %}
<div class="nav-bar">
    <div class="logo">
        <a href="{% url 'twitter:index' %}">Twitter</a>
    </div>
    <div class="login-out">
        {% if user.is_anonymous %}
        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
        {% else %}
        <a class="user-name" href="{% url 'twitter:mypage' user.id %}">
            <div class="user-pp">
                {% if user.pp %}
                <img src="{{ user.pp.url }}" alt="">
                {% else %}
                <i class="fa-solid fa-user"></i>
                {% endif %}
            </div>
            {{ user.username }}
        </a>
        <a class="nav-link" id="logout-btn" href="{% url 'common:logout' %}"data-uri="">로그아웃</a>
        {% endif %}
        {% if user.is_anonymous %}
        <a href="{% url 'common:signup' %}" class="nav-link2">회원가입</a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/twitter/main.html
{% extends 'base.html' %}
{% block content %}

<div class="twit-area">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
{% endif %}

    <form 
    {% if user.is_authenticated %}
    action="{% url 'twitter:twit_create' %}" 
    {% else %}
    action="{% url 'common:login' %}" 
    {% endif %}
    method="post" class="twit-form">
        {% csrf_token %}
        <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content" rows="10" 
        placeholder="{% if not user.is_authenticated %}로그인 해주세요{% else %}내용을 입력해주세요.{% endif %}"></textarea>
        <input type="submit" value="트윗하기" class="nav-link" {% if not user.is_authenticated %}disabled="disabled"{% endif %} >
    </form>
    {% include "twitter/twits.html" %}
</div>
{% endblock %}

templates/twitter/my_twits.html
{% extends 'base.html' %}
{% block content %}
<div class="profile-wrap">
    <div class="profile">
        <!-- 프로필영역 -->
        <div class="profile-text-wrap">
            <div class="profile-image">
                {% if my_twit.pp %}
                <img src="{{ my_twit.pp.url }}" alt="">
                {% else %}
                <i class="fa-solid fa-user"></i>
                {% endif %}
            </div>
            <div class="profile-text profile-setting-false">
                <p>{{ my_twit.username }}
                    {% if my_twit == request.user %}
                    <i class="fa-solid fa-gear setting-btn"></i>
                    {% endif %}
                </p>
                <span>
                    <i class="fa-solid fa-envelope"></i>
                    {{ my_twit.email }}
                </span>
            </div>
        </div>
        <!-- 프로필 수정 form -->
        <form action="{% url 'twitter:mypage' user_id=user.id %}" class="profile-form-wrap" method="post" style="display:none"  enctype="multipart/form-data">
            {% csrf_token %}
            <div class="profile-input">
                <input type="file" name="pp" id="pp"  style="display:none;" onchange="setThumbnail(event)"  accept=".jpg, .png, .gif" multiple/>
                <label for="pp" class="pp">
                    {% if my_twit.pp %}
                    <img src="{{ my_twit.pp.url }}" alt="" class="now-pp">
                    {% else %}
                    <div style="height:100%"></div>
                    {% endif %}
                    <div id="image_container"></div>
                    <div class="image-container">+</div>
                </label>
            </div>
            <div class="profile-text">
                <div>
                    <label for="username">닉네임</label>
                    <input type="text" name="username" id="username" value="{{ user.username }}" />
                </div>
                <div>
                    <label for="email">이메일</label>
                    <input type="text" name="email" id="email" value="{{ user.email }}" />
                </div>
                <input type="hidden" name="userid" id="userid" value="{{ user.id }}">
                <a class="nav-link2 setting-btn" style="width:auto">취소</a>
                <input type="submit" value="수정하기" class="setting-submit-btn nav-link">
            </div>
        </form>
    </div>
</div>
<div class="twit-area">
    {% include "twitter/twits.html" %}
</div>
{% endblock %}

templates/twitter/twit_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="twit-detail">
    <div class="twit-box now-twit">
        <div class="author">
            <a href="{% url "twitter:mypage" thistwit.author_id %}">
                <div class="user-pp">
                    {% if thistwit.author.pp %}
                    <img src="{{ thistwit.author.pp.url }}" alt="">
                    {% else %}
                    <i class="fa-solid fa-user"></i>
                    {% endif %}
                </div>
                {{ thistwit.author }}
            </a>
        </div>
        <p class="twit-content">{{ thistwit.content }}</p>
        <span class="twit-date">{{ thistwit.create_date }}</span>
        {% if thistwit.parent %}
        <div class="parent-twit">
            <a href="{% url 'twitter:detail' thistwit.parent.id %}">
                <p class="author">{{ thistwit.parent.author }}</p>
                <p class="twit-content">{{ thistwit.parent.content }}</p>
                <span class="twit-date">{{ thistwit.parent.create_date }}</span>
            </a>
        </div>
        {% endif %}
        <div class="twit-btns">
            <a href="javascript:void(0)" class="reply-btn" value="답글"/>
                <i class="fa-solid fa-comment-dots"></i>
                <span>{{ thistwit.get_my_children }}</span>
            </a>
            {% if thistwit.author == request.user %}
            <a href="javascript:void(0)" class="delete-btn" value="삭제" data-uri="{% url 'twitter:twit_delete' thistwit.id %}" >
                <i class="fa-regular fa-trash-can"></i>
            </a>
            {% endif %}
        </div>
        <div class="twit-form-wrap" style="display:none;">
            <i class="fa-solid fa-reply fa-rotate-180"></i>
            <form action="{% url 'twitter:twit_create' %}" method="post" class="twit-form">
                {% csrf_token %}
                {{ form.as_p }}
                <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="reply-content" rows="10" placeholder="{% if not user.is_authenticated %}로그인 해주세요{% else %}답글을 입력해주세요.{% endif %}"></textarea>
                <input type="hidden" name="parent" id="reply-parent" value="{{ thistwit.id }}">
                <input type="submit" value="답글하기" class="nav-link">
            </form>
        </div>
    </div>

    
    <div class="child-twit-list">
        {% for child in thread %}
        <i class="fa-solid fa-reply fa-rotate-180"></i>
        <div class="reply-box">
            <div class="author">
                <div class="user-pp">
                    {% if child.pp %}
                    <img src="{{ child.pp.url }}" alt="">
                    {% else %}
                    <i class="fa-solid fa-user"></i>
                    {% endif %}
                </div>
                {{ child.author }}
            </div>
            <a href="{% url 'twitter:detail' child.id %}" class="twit-hover">
                <div class="twit-content">{{ child.content }}</div>
                <div class="twit-date">{{ child.create_date }}</div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/twitter/twits.html
{% if twits %}
<ul class="twit-list">
    {% for twit in twits %}
    <li class="twit-box">
        <div class="author">
            <a href="{% url "twitter:mypage" twit.author_id %}">
                <div class="user-pp">
                    {% if twit.author.pp %}
                    <img src="{{ twit.author.pp.url }}" alt="">
                    {% else %}
                    <i class="fa-solid fa-user"></i>
                    {% endif %}
                </div>
                {{ twit.author }}
            </a>
        </div>
        <a href="{% url 'twitter:detail' twit.id %}" class="twit-hover">
            <p class="twit-content">
                {% if twit.parent %}
                <i class="fa-solid fa-reply fa-flip-horizontal"></i>
                {% endif %}
                {{ twit.content }}
            </p>
            <span class="twit-date">{{ twit.create_date }}</span>
        </a>
        {% if twit.parent %}
        <div class='parent-twit'>
            <a href="{% url 'twitter:detail' twit.parent.id %}">
                <p class="author">{{ twit.parent.author.username }}</p>
                <p class="twit-content">{{ twit.parent.content }}</p>
                <span class="twit-date">{{ twit.parent.create_date }}</span>
            </a>
        </div>
        {% endif %}
        <div class="twit-btns">
            <a href="javascript:void(0)" class="reply-btn" value="답글"/>
                <i class="fa-solid fa-comment-dots"></i>
                <span>{{ twit.get_my_children }}</span>
            </a>
            {% if twit.author == request.user %}
            <a href="javascript:void(0)" class="delete-btn" value="삭제" data-uri="{% url 'twitter:twit_delete' twit.id %}" >
                <i class="fa-regular fa-trash-can"></i>
            </a>
            {% endif %}
        </div>
        <div class="twit-form-wrap" style="display:none;">
            <i class="fa-solid fa-reply fa-rotate-180"></i>
            <form 
            {% if user.is_authenticated %}
            action="{% url 'twitter:twit_create' %}" 
            {% else %}
            action="{% url 'common:login' %}" 
            {% endif %}
            method="post" class="twit-form">
                {% csrf_token %}
                <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="reply-content" rows="10" placeholder="{% if not user.is_authenticated %}로그인 해주세요{% else %}답글을 입력해주세요.{% endif %}"></textarea>
                <input type="hidden" name="parent" id="reply-parent" value="{{ twit.id }}">
                <input type="submit" value="답글하기" class="nav-link" {% if not user.is_authenticated %}disabled="disabled"{% endif %}  >
            </form>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/users/profile.html
{% extends 'base.html' %}
{% block content %}
<table>
    <tr>
        <td>아이디</td>
        {% if user.level == '0' %}
        <td>{{ user.user_id }} 회원</td>
        {% elif %}
        <td>{{ user.user_id }} 관리자</td>
        {% endif %}
    </tr>
    <tr>
        <td>이메일</td>
        <td>{{ user.email }}</td>
    </tr>
    <tr>
        <td>이름</td>
        <td>{{ user.name }}</td>
    </tr>
</table>
{% endblock %}